from setuptools import setup

setup(name='pytest-zap',
      version='0.1',
      description='OWASP ZAP plugin for py.test.',
      author='Dave Hunt',
      author_email='dhunt@mozilla.com',
      url='https://github.com/davehunt/pytest-zap',
      py_modules=['pytest_zap'],
      install_requires=['pytest', 'python-owasp-zap-v2'],
      entry_points={'pytest11': ['pytest_zap = pytest_zap']},
      license='Mozilla Public License 2.0 (MPL 2.0)',
      keywords='py.test pytest owasp zap test security mozilla',
      classifiers=['Development Status :: 4 - Beta',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
                   'Operating System :: POSIX',
                   'Operating System :: Microsoft :: Windows',
                   'Operating System :: MacOS :: MacOS X',
                   'Topic :: Software Development :: Quality Assurance',
                   'Topic :: Software Development :: Testing',
                   'Topic :: Utilities',
                   'Programming Language :: Python',
                   'Programming Language :: Python :: 2.6',
                   'Programming Language :: Python :: 2.7'])
